version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: cinema-mongodb
    environment:
      MONGO_INITDB_DATABASE: admin
    restart: always
    ports:
      - 10009:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo-volumn:/data/db
